[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
    "dotnet restore TripWiseJa.sln",
    "dotnet publish src/TripWiseJa.API/TripWiseJa.API.csproj -c Release -o /app/out"
]

[start]
cmd = "cd /app/out && ./TripWiseJa.API"
